name: workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repositor
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with: 
        arguments: build
        build-root-directory: api/

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
    - name: Check out Git repositor
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16 # TODO - what node version?
    - run: npm ci
    - run: npm test
  
  test-backend-gradle:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
    - name: Check out Git repositor
      uses: actions/checkout@v3
    - name: Testing with Gradlew
      run: gradle test
    
  test-backend-newman:
    # TODO - what resources do we need for these tests?
    needs: build-backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # TODO 
    - name: Check out Git repositor
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install  
      
    - name: Install newman
      run: npm install -g newman

    - name: Make directory for Test Results
      run: mkdir -p testArtifacts
    
    - name: Run the API and Postman Collection
      run: | 
        npm run start:dev &
        sleep 60
        newman run //api.getpostman.com/collections/{{ secrets.CID }}?apikey={{ secrets.POSTMAN_API_KEY}}

    - name: Output test results
      uses: actions/upload-artifact@v2
      with:
        name: PostmanReports
        path: testArtifacts

  